language: ruby

rvm:
  - 2.1.0

bundler_args: --without development:production

script:
  - ruby setup.rb
  - bundle exec rake db:create db:migrate spec

notifications:
  email:
    recipients:
    - ameutau@gmail.com
    - kitaitimakoto@gmail.com
    on_success: change
    on_failure: always
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#shikakun"
