github:
  client_id: '<%= ENV['GITHUB_CLIENT_ID'] %>'
  client_secret: '<%= ENV['GITHUB_CLIENT_SECRET'] %>'
twitter:
  consumer_key: '<%= ENV['TWITTER_CONSUMER_KEY'] %>'
  consumer_secret: '<%= ENV['TWITTER_CONSUMER_SECRET'] %>'
  oauth_token: '<%= ENV['TWITTER_OAUTH_TOKEN'] %>'
  oauth_token_secret: '<%= ENV['TWITTER_OAUTH_TOKEN_SECRET'] %>'
snippet:
  salt: '<%= ENV['SNIPPET_SALT'] %>'
