github:
  client_id: '<%= ENV["GITHUB_CLIENT_ID"] %>'
  client_secret: '<%= ENV["GITHUB_CLIENT_SECRET"] %>'
twitter:
  consumer_key: '<%= ENV["TWITTER_CONSUMER_KEY"] %>'
  consumer_secret: '<%= ENV["TWITTER_CONSUMER_SECRET"] %>'
  access_token: '<%= ENV["TWITTER_ACCESS_TOKEN"] %>'
  access_token_secret: '<%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>'
snippet:
  salt: '<%= ENV["SNIPPET_SALT"] %>'
